name: Create Release and Docker Build

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract vars from payload
      id: vars
      run: |
        echo "SERVICE_NAME"=${{ github.event.client_payload.service_name }}" >> $GITHUB_ENV
        echo "RELEASE_VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
        echo "IMAGE_REGISTRY"=${{ github.event.client_payload.image_registry }}" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/sre-playground-378016/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
